version: '3.3'

# docker compose up dev
services:
  dev:
    container_name: todo_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      dockerfile: ./dockerfile
    command: npm run start:dev
    ports:
      - 9001:9001
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./database:/data/db
    ports:
      - 8001:8001
    networks:
      - nesjs-network
    restart: always
  prod:
    container_name: todo_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      dockerfile: ./dockerfile
    command: npm run start:prod
    ports:
      - 9090:9090
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
networks:
  nesjs-network:
    driver: bridge